### ISSUE TITLE
Has the app been depublished on Google Play?

### ISSUE THREAD

**Issue by Lineflyer** [cjmoran/cgeo-wear#20]
Hi, this is @Lineflyer from c:geo team:
Due to recent support questions we received I have the following question:
Is c:geo wear still available on Google Play? Some users mentioned it is no longer available...

**Comment by cjmoran** [comment]
Hey Lineflyer,

Yeah, I unpublished it from Google Play because I sadly don't have the time to support it anymore. The latest apk can still be downloaded from the releases page here, but the repo isn't maintained anymore. Sorry about that!

**Comment by Lineflyer** [comment]
Hi @cjmoran ,

do you have any plans to take it up again.
Otherwise:
It would be a shame if this just passes away. Maybe you could think about handing it over to the c:geo team and giving it into opensource licensing. This way we could at least preserve the current state and offer it to developers interested in maintaining and/or continuing it. We could put it into our repository then.

**Comment by cjmoran** [comment]
Sure, that would be fine with me. What would you need me to do?

**Comment by Lineflyer** [comment]
Not sure, will ask our developer team.
